spring.application.name=bookedNbusy
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/bookednbusydatabase?createTableIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookednbusyshow@gmail.com
spring.mail.password=1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true