spring.application.name=bookedNbusy
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/bookednbusydatabase?createTableIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update